duckdb:
  outputs:
    scaleway:
      type: postgres
      threads: 1
      database: dbt
      host: 51.158.129.26
      user: niels
      password: "pe[0K{[U7f@!]R:w"
      port: 14996
      schema: analytics
  target: scaleway
